version: '3.9'

services:
  app:
    image: ruby:3.2
    container_name: rails_app
    working_dir: /app
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - PORT=3000
    stdin_open: true
    tty: true
    command: bash -c "bundle install && rails server -b 0.0.0.0"

volumes:
  bundle_cache:
